### ISSUE TITLE
init.lua

### ISSUE THREAD

**Issue by publicmatt** [Diego-Llanes/dev-tools#1]
Is this project abandoned? If it needs a new maintainer, I'd be willing to fork it.

Also, can't find slack bot repo.

**Comment by Diego-Llanes** [comment]
> Is this project abandoned? If it needs a new maintainer, I'd be willing to fork it.
> 
> 
> 
> Also, can't find slack bot repo.

Maintainers alive and well. banned, blocked, gg no re.
